Repository emilk/egui_plot, pull requests merged in 2024-12, with the labels that each got.

#43 Use `Vec2b` in parameters
  Cargo.lock
  demo/src/plot_demo.rs
  egui_plot/src/lib.rs
  egui_plot/src/transform.rs
  scripts/check.sh
Labels: include in changelog

#60 Fix axis thickness for multiple X or Y axes
  egui_plot/src/lib.rs
Labels: bug, include in changelog

#57 Fix axis labels overlap with axis ticks
  demo/src/plot_demo.rs
  egui_plot/src/axis.rs
Labels: bug, include in changelog

#51 Add `PlotUi::add_item(Box<dyn PlotItem>)`
  egui_plot/src/plot_ui.rs
Labels: enhancement, include in changelog

#47 Implement custom ruler color for Plot
  egui_plot/src/lib.rs
Labels: enhancement, include in changelog

#59 Update to egui `0.30.0`, MSRV to 1.80
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  clippy.toml
  demo/src/plot_demo.rs
  deny.toml
  examples/custom_plot_manipulation/Cargo.toml
  examples/save_plot/Cargo.toml
  examples/save_plot/src/main.rs
  rust-toolchain
  scripts/check.sh
  scripts/clippy_wasm/clippy.toml
Labels: include in changelog

#61 Update infra with stuff from rerun_template repo
  .gitattributes
  .github/workflows/cargo_machete.yml
  .github/workflows/links.yml
  .github/workflows/rust.yml
  Cargo.toml
  RELEASES.md
  rust-toolchain
  scripts/generate_changelog.py
  scripts/template_update.py
Labels: exclude from changelog
