Repository emilk/egui_plot, pull requests merged in 2025-06, with the labels that each got.

#110 Add `PlotUi::set_plot_bounds_x` and `set_plot_bounds_y`
  egui_plot/src/lib.rs
  egui_plot/src/plot_ui.rs
Labels: enhancement, include in changelog

#102 Allow zooming one axis by dragging it
  egui_plot/src/lib.rs
Labels: enhancement, include in changelog

#112 Add a background behind all text that is shown on hover
  egui_plot/src/items/mod.rs
  egui_plot/src/lib.rs
Labels: include in changelog

#113 Fix plot axis sometimes being way too thick
  demo/tests/snapshots/demos/Charts.png
  demo/tests/snapshots/demos/Custom Axes.png
  demo/tests/snapshots/demos/Interaction.png
  demo/tests/snapshots/demos/Items.png
  demo/tests/snapshots/demos/Legend.png
  demo/tests/snapshots/demos/Lines.png
  demo/tests/snapshots/demos/Linked Axes.png
  demo/tests/snapshots/demos/Markers.png
  demo/tests/snapshots/light_mode.png
  demo/tests/snapshots/scale_0.50.png
  demo/tests/snapshots/scale_1.00.png
  demo/tests/snapshots/scale_1.39.png
  demo/tests/snapshots/scale_2.00.png
  egui_plot/src/axis.rs
  egui_plot/src/lib.rs
Labels: bug, include in changelog

#104 Bump Rust Version and fix Plot Item Visibility in Demo
  .vscode/settings.json
  README.md
  demo/src/plot_demo.rs
  egui_plot/src/lib.rs
Labels: include in changelog

#116 Update MSRV to 1.85 and bump rust edition to 2024
  .github/workflows/cargo_shear.yml
  .github/workflows/enforce_branch_name.yml
  .github/workflows/rust.yml
  .vscode/settings.json
  Cargo.toml
  clippy.toml
  demo/src/plot_demo.rs
  demo/tests/plot.rs
  egui_plot/src/axis.rs
  egui_plot/src/items/bar.rs
  egui_plot/src/items/box_elem.rs
  egui_plot/src/items/mod.rs
  egui_plot/src/items/values.rs
  egui_plot/src/legend.rs
  egui_plot/src/lib.rs
  egui_plot/src/plot_ui.rs
  egui_plot/src/transform.rs
  rust-toolchain
  scripts/check.sh
  scripts/clippy_wasm/clippy.toml
  scripts/template_update.py
Labels: include in changelog

#118 Revert egui update
  Cargo.lock
  demo/tests/snapshots/demos/Charts.png
  demo/tests/snapshots/demos/Lines.png
  demo/tests/snapshots/demos/Linked Axes.png
  demo/tests/snapshots/demos/Markers.png
  demo/tests/snapshots/light_mode.png
  demo/tests/snapshots/scale_1.00.png
  egui_plot/src/items/mod.rs
Labels: exclude from changelog
