Repository emilk/egui_plot, pull requests merged in 2025-02, with the labels that each got.

#71 Add kittest snapshot tests
  .gitattributes
  .github/workflows/rust.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  demo/Cargo.toml
  demo/src/plot_demo.rs
  demo/tests/plot.rs
  demo/tests/snapshots/demos/Charts.png
  demo/tests/snapshots/demos/Custom Axes.png
  demo/tests/snapshots/demos/Interaction.png
  demo/tests/snapshots/demos/Items.png
  demo/tests/snapshots/demos/Legend.png
  demo/tests/snapshots/demos/Lines.png
  demo/tests/snapshots/demos/Linked Axes.png
  demo/tests/snapshots/demos/Markers.png
  demo/tests/snapshots/light_mode.png
  demo/tests/snapshots/scale_0.50.png
  demo/tests/snapshots/scale_1.00.png
  demo/tests/snapshots/scale_1.39.png
  demo/tests/snapshots/scale_2.00.png
  deny.toml
  egui_plot/src/lib.rs
Labels: enhancement, exclude from changelog

#64 Allow borrowing plot points
  Cargo.lock
  Cargo.toml
  demo/src/plot_demo.rs
  egui_plot/src/items/mod.rs
  egui_plot/src/items/values.rs
  egui_plot/src/legend.rs
  egui_plot/src/lib.rs
  egui_plot/src/plot_ui.rs
  examples/borrow_points/Cargo.toml
  examples/borrow_points/README.md
  examples/borrow_points/src/main.rs
Labels: enhancement, include in changelog

#65 Add `insertion_order` and `color_conflict_handling` to `Legend`
  Cargo.lock
  egui_plot/src/legend.rs
  egui_plot/src/lib.rs
  examples/legend_sort/Cargo.toml
  examples/legend_sort/README.md
  examples/legend_sort/src/main.rs
Labels: enhancement, include in changelog

#72 Update to egui 0.31.0
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  demo/Cargo.toml
  demo/tests/snapshots/demos/Charts.png
  demo/tests/snapshots/demos/Interaction.png
  demo/tests/snapshots/demos/Items.png
  demo/tests/snapshots/demos/Legend.png
  demo/tests/snapshots/demos/Lines.png
  demo/tests/snapshots/demos/Linked Axes.png
  demo/tests/snapshots/demos/Markers.png
  demo/tests/snapshots/light_mode.png
  demo/tests/snapshots/scale_0.50.png
  demo/tests/snapshots/scale_1.00.png
Labels: include in changelog

#81 Legend reports its hovered item now to the plot's response
  egui_plot/src/legend.rs
  egui_plot/src/lib.rs
  egui_plot/src/memory.rs
Labels: include in changelog

#82 Plot items now require an id
  demo/src/plot_demo.rs
  egui_plot/src/items/mod.rs
  egui_plot/src/legend.rs
  egui_plot/src/lib.rs
  egui_plot/src/memory.rs
  examples/borrow_points/src/main.rs
  examples/custom_plot_manipulation/src/main.rs
  examples/legend_sort/src/main.rs
  examples/save_plot/src/main.rs
Labels: include in changelog
