Repository emilk/egui_plot, pull requests merged in 2025-01, with the labels that each got.

#63 Update to latest egui
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  egui_plot/src/items/mod.rs
  egui_plot/src/lib.rs
Labels: include in changelog

#68 axis: fix label thickness
  egui_plot/src/axis.rs
Labels: bug, include in changelog

#69 Update MSRV to Rust 1.81
  .github/workflows/rust.yml
  Cargo.toml
  clippy.toml
  examples/custom_plot_manipulation/Cargo.toml
  examples/save_plot/Cargo.toml
  rust-toolchain
  scripts/check.sh
  scripts/clippy_wasm/clippy.toml
Labels: include in changelog

#70 Update to latest egui master
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  deny.toml
  egui_plot/src/items/bar.rs
  egui_plot/src/items/box_elem.rs
  egui_plot/src/items/mod.rs
  egui_plot/src/lib.rs
Labels: exclude from changelog
