Repository emilk/egui_plot, pull requests merged in 2025-04, with the labels that each got.

#93 Fix CI
  .github/workflows/cargo_shear.yml
  RELEASES.md
  deny.toml
  lychee.toml
Labels: exclude from changelog

#90 Provide new functions to specify the default bounds
  egui_plot/src/lib.rs
Labels: enhancement, include in changelog

#94 Cargo update
  Cargo.lock
Labels: exclude from changelog

#95 Use workspace-defined rust version etc
  examples/borrow_points/Cargo.toml
  examples/custom_plot_manipulation/Cargo.toml
  examples/legend_sort/Cargo.toml
  examples/save_plot/Cargo.toml
Labels: exclude from changelog

#96 Fix dynamic bounds modifications
  egui_plot/src/lib.rs
Labels: bug, include in changelog
